stages:
    - build
    - deploy

build:
  tags: 
      - server
  stage: build
  script: 
      - composer install -o --no-dev
      - mkdir /var/www/sources/$CI_PIPELINE_ID
      - cp -r * /var/www/sources/$CI_PIPELINE_ID
      - php /var/www/sources/$CI_PIPELINE_ID/bin/createConfig.php --dbuser $DB_USER --dbhost $DB_HOST --dbpass $DB_PASS --database $DB_NAME --tgkey $TG_KEY --mapskey $MAP_KEY --webhost $WEB_HOST
      - mkdir -p /var/www/sources/$CI_PIPELINE_ID/templates/cache/
      - chmod 777 /var/www/sources/$CI_PIPELINE_ID/templates/cache/
  only:
    - main

deploy:
  tags: 
    - server
  stage: deploy
  script:
    - rm /var/www/travel
    - ln -s /var/www/sources/$CI_PIPELINE_ID /var/www/travel
    - ln -s /var/www/img /var/www/travel/www/img
    - sudo service php7.4-fpm restart
    - sudo /usr/sbin/nginx -t
    - sudo /usr/sbin/nginx -s reload
    - sudo rm -rf `ls -trd /var/www/sources/* |head  -n -20`
  only:
    - main